services:
  backend:
    build:
      context: ./
    container_name: backend_container
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://21amir21:test123@db:5432/tasksDB
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: 21amir21
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: tasksDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
